### ISSUE TITLE
en.json for the UI

### ISSUE THREAD

**Issue by rectulo** [itamarcu/pf2e-modifiers-matter#7]
Is it possible to also localize the UI of your module ? 

If you can provide an en.json, I will provide the fr.json.

**Comment by itamarcu** [comment]
I can do that, sure.  Additionally, I'd like the localization to work with the actual logic, but sadly it includes some hardcoded English names:

```js
    'Devise a Stratagem', // Investigator
    'Wild Shape', // Druid
    'Hunter\'s Edge: Flurry', // Ranger, replaces multiple attack penalty
    'Flurry', // same
    'Effect: Hunter\'s Edge, Flurry', // Ranger's companion
```

(I used the preexisting core translations for everything else, e.g. "PF2E.NPC.Adjustment.EliteLabel" instead of "Elite", but these ones are specific items)

Does your group use an automatic french translation for these things?  If so, can you share the translation with me?

**Comment by rectulo** [comment]
I can't help you with unlocalized values.
1. Maybe, we can ask the dev of the PF2 system to add those in the en.json of the system for helping to translate them 
2. have your own in your module but It's a loss of time for me to maintain two or more projects
3. We also have all these unlocalized terms in our compendium. you can find a glossary [here](https://gitlab.com/pathfinder-fr/foundryvtt-pathfinder2-fr/-/blob/master/data/dictionnaire.md) with the english word(s), the french and the ID of the item.

We are using Babele with the french compendia and all the terms above are already translated.
Alas, I'm not a "true" coder or a dev. 
I'm just a translator who use what other have coded for me. I'm just trying to match what I understand.

**Comment by itamarcu** [comment]
The glossary is great - thank you!  I can use it myself, and maintenance will not be necessary for you or anyone else, hopefully.

**Comment by itamarcu** [comment]
Added in v1.3.0, thank you!
